name: Kubernetes Access Test

on:
  workflow_dispatch:

jobs:
  test-kubernetes-access:
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Set up Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Configure Kubernetes context
        run: |
          kubectl config set-cluster my-cluster --server=https://<your-kubernetes-api-server> --insecure-skip-tls-verify=true
          kubectl config set-credentials my-user --token=<your-kubernetes-token>
          kubectl config set-context my-context --cluster=my-cluster --user=my-user
          kubectl config use-context my-context

      - name: Generate random release name
        id: rand
        run: echo "RELEASE_NAME=demo-$(openssl rand -hex 4)" >> $GITHUB_ENV

      - name: Install nginx via Helm with overridden values
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          helm upgrade --install ${RELEASE_NAME} bitnami/nginx \
            --namespace <your-namespace> \
            --create-namespace \
            --set image.tag=alpine

      - name: Check for Helm releases in namespace
        run: |
          helm list -n <your-namespace>